<?php
/**
 * @var $block \Barwenock\VideoImport\Block\Adminhtml\Upload
 */
?>
<div class="import-video">
    <form id="import-form" class="admin__fieldset" action="<?php echo $block->getFormAction(); ?>"
          method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
        <label for="file_upload">Choose a file:</label>
        <input type="file" name="file_upload" id="file_upload" />
        <button type="submit" name="submit" value="submit">Upload File & Import</button>
    </form>
</div>

<div class="export-video">
    <form id="export-form" class="admin__fieldset" action="<?php echo $block->getExportAction(); ?>"
          method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
        <button type="submit" name="submit" value="submit">Export Videos CSV</button>
    </form>
</div>
